#!/bin/sh
#
# ひとつの ssh-agent プロセスを使いまわす
# 環境変数をセットするため source single-ssh-agent で実行する
#

DOT_FILE=~/.single-ssh-agent
SSH_AGENT_PID=0

if [ -f $DOT_FILE ] ; then
    source $DOT_FILE > /dev/null
    ps -p $SSH_AGENT_PID > /dev/null
    if [ $? -eq 0 ] ; then
        echo Agent pid $SSH_AGENT_PID
    else
        echo Agent pid $SSH_AGENT_PID is killed
        SSH_AGENT_PID=0
    fi
fi

if [ $SSH_AGENT_PID -le 0 ] ; then
    ssh-agent > $DOT_FILE
    source $DOT_FILE
    ssh-add
fi
