#!/bin/sh
#
# ひとつの ssh-agent プロセスを使いまわす
#

DOT_FILE=~/.single-ssh-agent

if [ -f $DOT_FILE ] ; then
    source $DOT_FILE
    ps -p $SSH_AGENT_PID > /dev/null
    if [ $? -eq 0 ] ; then
        exit 0
    else
        echo $SSH_AGENT_PID is killed
    fi
fi

ssh-agent > $DOT_FILE
source $DOT_FILE
ssh-add
