# Reference Page
# http://journal.mycom.co.jp/column/zsh/index.html

autoload -U compinit
compinit

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt hist_ignore_dups
setopt share_history

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

#autoload predict-on
#predict-on

setopt auto_cd
setopt auto_pushd
setopt correct
setopt list_packed
setopt nolistbeep

#PROMPT="${USER}@${HOST}> "
PROMPT="%D{%H:%M:%S}> "
RPROMPT="[%/]"
PROMPT2="{%_} "
SPROMPT="%r is correct? [n,y,a,e]"
re-prompt () {
    zle .reset-prompt
    zle .accept-line
}
zle -N accept-line re-prompt

#autoload -Uz vcs_info
#setopt prompt_subst
#zstyle ':vcs_info:git:*' check-for-changes true
#zstyle ':vcs_info:git:*' stagedstr "%F{yellow}"
#zstyle ':vcs_info:git:*' unstagedstr "%F{red}"
#zstyle ':vcs_info:*' formats "%F{green}%c%u[%b]%f"
#zstyle ':vcs_info:*' actionformats '[%b|%a]'
#kprecmd () { vcs_info }
#RPROMPT=$RPROMPT'${vcs_info_msg_0_}'

export LANG=ja_JP.UTF-8

alias la="ls -aF"
alias ll="ls -lF"
alias li="ls -F"

[ -f ~/.zshrc.local ] && source ~/.zshrc.local

#source single-ssh-agent
if ssh-add -l |grep -q $(cat ~/.ssh/id_rsa.pub | sed -e 's/^.*== //')
    then :
    else ssh-add
fi
